import "server-only";

import ExcelJS from "exceljs";
import type { ReportTable } from "./export";

const FORMULA_TRIGGER = /^[=+\-@\t\r]/;

function safeCell(value: string | number): string | number {
  // An explicit em dash is the most portable missing-value marker: empty
  // shared strings leak their index in some readers, while omitted styled
  // cells can render transparent/black in previews.
  if (value === "") return "—";
  return typeof value === "string" && FORMULA_TRIGGER.test(value) ? `'${value}` : value;
}

function numberFormat(column: string): string {
  const name = column.toLowerCase();
  if (name.includes("date")) return "yyyy-mm-dd";
  if (name.includes("%") || name.includes("margin") || name.includes("deadhead")) return '0.0"%"';
  if (name.includes("amount") || name.includes("cost") || name.includes("revenue") || name.includes("profit") || name.includes("rate") || name.includes("tax due")) return '$#,##0.00;[Red]-$#,##0.00';
  if (name.includes("mile") || name.includes("gallon") || name.includes("gal.")) return '#,##0.00';
  return '#,##0.00';
}

/** Native Excel export with frozen headers, filters, print setup, and typed numeric cells. */
export async function toXlsx(table: ReportTable): Promise<Uint8Array> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Onroad Books";
  workbook.created = new Date();
  workbook.modified = new Date();
  workbook.calcProperties.fullCalcOnLoad = true;
  const sheet = workbook.addWorksheet("Report", {
    views: [{ state: "frozen", ySplit: 3 }],
    pageSetup: { orientation: table.columns.length > 7 ? "landscape" : "portrait", fitToPage: true, fitToWidth: 1, fitToHeight: 0, margins: { left: 0.25, right: 0.25, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 } },
  });
  sheet.mergeCells(1, 1, 1, Math.max(1, table.columns.length));
  const title = sheet.getCell(1, 1);
  title.value = table.title;
  title.font = { name: "Aptos Display", size: 16, bold: true, color: { argb: "FFFFFFFF" } };
  title.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF17324D" } };
  title.alignment = { vertical: "middle" };
  sheet.getRow(1).height = 30;
  sheet.mergeCells(2, 1, 2, Math.max(1, table.columns.length));
  const generated = sheet.getCell(2, 1);
  generated.value = `Generated by Onroad Books • ${new Date().toISOString().slice(0, 10)}`;
  generated.font = { italic: true, size: 9, color: { argb: "FF536273" } };
  const header = sheet.getRow(3);
  header.values = table.columns;
  header.font = { bold: true, color: { argb: "FFFFFFFF" } };
  header.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF2E5D7B" } };
  header.alignment = { vertical: "middle", wrapText: true };
  header.height = 28;

  for (const row of table.rows) sheet.addRow(row.map(safeCell));
  sheet.autoFilter = { from: { row: 3, column: 1 }, to: { row: 3, column: table.columns.length } };
  sheet.columns.forEach((column, index) => {
    const values = [table.columns[index], ...table.rows.slice(0, 200).map((row) => String(row[index] ?? ""))];
    column.width = Math.min(38, Math.max(11, ...values.map((value) => value.length + 2)));
  });
  for (let rowNumber = 4; rowNumber <= sheet.rowCount; rowNumber += 1) {
    const row = sheet.getRow(rowNumber);
    row.alignment = { vertical: "top", wrapText: false };
    // Give every row an opaque fill. Besides making banding consistent, this
    // prevents transparent blank cells from rendering black in some viewers.
    row.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: rowNumber % 2 === 0 ? "FFF3F7FA" : "FFFFFFFF" },
    };
    row.eachCell((cell, columnNumber) => {
      cell.border = { bottom: { style: "hair", color: { argb: "FFDCE4EA" } } };
      if (typeof cell.value === "number") cell.numFmt = numberFormat(table.columns[columnNumber - 1] ?? "");
    });
  }
  sheet.headerFooter.oddFooter = "Onroad Books  |  &P of &N";
  const buffer = await workbook.xlsx.writeBuffer();
  return new Uint8Array(buffer);
}
