import { sql } from "drizzle-orm";
import { boolean, date, foreignKey, index, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/pg-core";
import * as enums from "./enums";
import { business } from "./businesses";
import { driver } from "./drivers";
import { truck } from "./trucks";

export const load = pgTable("Load", {
  id: text("id").primaryKey(),
  businessId: text("businessId").notNull(),
  truckId: text("truckId").notNull(),
  driverId: text("driverId"),
  date: date("date", { mode: "string" }).notNull(),
  deliveryDate: date("deliveryDate", { mode: "string" }),
  endingOdometer: integer("endingOdometer"),
  originCity: text("originCity").notNull(),
  originState: varchar("originState", { length: 2 }).notNull(),
  destinationCity: text("destinationCity").notNull(),
  destinationState: varchar("destinationState", { length: 2 }).notNull(),
  broker: text("broker"),
  brokerContact: text("brokerContact"),
  loadNumber: text("loadNumber"),
  equipmentType: enums.equipmentType("equipmentType"),
  loadCapacity: enums.loadCapacity("loadCapacity"),
  equipmentLengthFt: integer("equipmentLengthFt"),
  weightLbs: integer("weightLbs"),
  commodity: text("commodity"),
  loadedMiles: integer("loadedMiles").notNull(),
  deadheadMiles: integer("deadheadMiles").notNull().default(0),
  grossRate: numeric("grossRate", { precision: 12, scale: 2 }).notNull(),
  fuelCost: numeric("fuelCost", { precision: 12, scale: 2 }).notNull().default(sql`0`),
  tolls: numeric("tolls", { precision: 12, scale: 2 }).notNull().default(sql`0`),
  dispatchFee: numeric("dispatchFee", { precision: 12, scale: 2 }).notNull().default(sql`0`),
  factoringFee: numeric("factoringFee", { precision: 12, scale: 2 }).notNull().default(sql`0`),
  otherExpenses: numeric("otherExpenses", { precision: 12, scale: 2 }).notNull().default(sql`0`),
  driverPay: numeric("driverPay", { precision: 12, scale: 2 }).notNull().default(sql`0`),
  costsPosted: boolean("costsPosted").notNull().default(false),
  status: enums.paymentStatus("status").notNull().default("PENDING"),
  jurisdictionMiles: jsonb("jurisdictionMiles").notNull().default(sql`'[]'::jsonb`),
  invoiceNumber: text("invoiceNumber"),
  invoiceDate: date("invoiceDate", { mode: "string" }),
  invoiceDueDate: date("invoiceDueDate", { mode: "string" }),
  invoicePaidDate: date("invoicePaidDate", { mode: "string" }),
  billToName: text("billToName"),
  billToEmail: text("billToEmail"),
  billToAddress: text("billToAddress"),
  invoiceNotes: text("invoiceNotes"),
  notes: text("notes"),
  createdAt: timestamp("createdAt", { precision: 3, mode: "date", withTimezone: false }).notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: timestamp("updatedAt", { precision: 3, mode: "date", withTimezone: false }).notNull().$onUpdateFn(() => new Date()),
}, (table) => [
  index("Load_businessId_date_idx").on(table.businessId, table.date),
  index("Load_truckId_date_idx").on(table.truckId, table.date),
  index("Load_driverId_date_idx").on(table.driverId, table.date),
  index("Load_status_idx").on(table.status),
  uniqueIndex("Load_businessId_invoiceNumber_key").on(table.businessId, table.invoiceNumber),
  foreignKey({ name: "Load_businessId_fkey", columns: [table.businessId], foreignColumns: [business.id] }).onDelete("cascade").onUpdate("cascade"),
  foreignKey({ name: "Load_truckId_fkey", columns: [table.truckId], foreignColumns: [truck.id] }).onDelete("cascade").onUpdate("cascade"),
  foreignKey({ name: "Load_driverId_fkey", columns: [table.driverId], foreignColumns: [driver.id] }).onDelete("set null").onUpdate("cascade"),
]);
